disabled_rules:
- line_length
- vertical_whitespace
- trailing_whitespace
- function_body_length
- trailing_newline
- unused_optional_binding
- force_cast
- identifier_name
- large_tuple
- unneeded_synthesized_initializer
